package lexer

import (
	python3 "github.com/shirou/antlr-grammars-v4-go/python3"

	"github.com/shirou/golightan"
)

func NewPython3TokenMap() TokenMap {
	return TokenMap{
		symbolicMap: newPython3SymbolicMap(),
		ruleMap:     newPython3RuleMap(),
	}
}

func newPython3RuleMap() RuleMap {
	return RuleMap{
		Rule{python3.Python3ParserRULE_tfpdef,
			python3.Python3ParserNAME}: golightan.TokenTypeKeyword,
		//		Rule{python3.Python3ParserRULE_atom, python3.Python3ParserNAME}: golightan.TokenTypeKeyword,
	}
}

func newPython3SymbolicMap() TypeMap {
	return TypeMap{
		python3.Python3LexerSTRING:             golightan.TokenTypeText,
		python3.Python3LexerNUMBER:             golightan.TokenTypeKeyword,
		python3.Python3LexerINTEGER:            golightan.TokenTypeNumberInteger,
		python3.Python3LexerDEF:                golightan.TokenTypeKeyword,
		python3.Python3LexerRETURN:             golightan.TokenTypeKeyword,
		python3.Python3LexerRAISE:              golightan.TokenTypeKeyword,
		python3.Python3LexerFROM:               golightan.TokenTypeKeyword,
		python3.Python3LexerIMPORT:             golightan.TokenTypeKeywordNamespace,
		python3.Python3LexerAS:                 golightan.TokenTypeKeyword,
		python3.Python3LexerGLOBAL:             golightan.TokenTypeKeyword,
		python3.Python3LexerNONLOCAL:           golightan.TokenTypeKeyword,
		python3.Python3LexerASSERT:             golightan.TokenTypeKeyword,
		python3.Python3LexerIF:                 golightan.TokenTypeKeyword,
		python3.Python3LexerELIF:               golightan.TokenTypeKeyword,
		python3.Python3LexerELSE:               golightan.TokenTypeKeyword,
		python3.Python3LexerWHILE:              golightan.TokenTypeKeyword,
		python3.Python3LexerFOR:                golightan.TokenTypeKeyword,
		python3.Python3LexerIN:                 golightan.TokenTypeKeyword,
		python3.Python3LexerTRY:                golightan.TokenTypeKeyword,
		python3.Python3LexerFINALLY:            golightan.TokenTypeKeyword,
		python3.Python3LexerWITH:               golightan.TokenTypeKeyword,
		python3.Python3LexerEXCEPT:             golightan.TokenTypeKeyword,
		python3.Python3LexerLAMBDA:             golightan.TokenTypeKeyword,
		python3.Python3LexerOR:                 golightan.TokenTypeKeyword,
		python3.Python3LexerAND:                golightan.TokenTypeKeyword,
		python3.Python3LexerNOT:                golightan.TokenTypeKeyword,
		python3.Python3LexerIS:                 golightan.TokenTypeKeyword,
		python3.Python3LexerNONE:               golightan.TokenTypeKeyword,
		python3.Python3LexerTRUE:               golightan.TokenTypeKeyword,
		python3.Python3LexerFALSE:              golightan.TokenTypeKeyword,
		python3.Python3LexerCLASS:              golightan.TokenTypeKeyword,
		python3.Python3LexerYIELD:              golightan.TokenTypeKeyword,
		python3.Python3LexerDEL:                golightan.TokenTypeKeyword,
		python3.Python3LexerPASS:               golightan.TokenTypeKeyword,
		python3.Python3LexerCONTINUE:           golightan.TokenTypeKeyword,
		python3.Python3LexerBREAK:              golightan.TokenTypeKeyword,
		python3.Python3LexerASYNC:              golightan.TokenTypeKeyword,
		python3.Python3LexerAWAIT:              golightan.TokenTypeKeyword,
		python3.Python3LexerNEWLINE:            golightan.TokenTypeText,
		python3.Python3LexerNAME:               golightan.TokenTypeNameNamespace,
		python3.Python3LexerSTRING_LITERAL:     golightan.TokenTypeText,
		python3.Python3LexerBYTES_LITERAL:      golightan.TokenTypeText,
		python3.Python3LexerDECIMAL_INTEGER:    golightan.TokenTypeNumberInteger,
		python3.Python3LexerOCT_INTEGER:        golightan.TokenTypeKeyword,
		python3.Python3LexerHEX_INTEGER:        golightan.TokenTypeKeyword,
		python3.Python3LexerBIN_INTEGER:        golightan.TokenTypeKeyword,
		python3.Python3LexerFLOAT_NUMBER:       golightan.TokenTypeKeyword,
		python3.Python3LexerIMAG_NUMBER:        golightan.TokenTypeKeyword,
		python3.Python3LexerDOT:                golightan.TokenTypeKeyword,
		python3.Python3LexerELLIPSIS:           golightan.TokenTypeKeyword,
		python3.Python3LexerSTAR:               golightan.TokenTypeOperator,
		python3.Python3LexerOPEN_PAREN:         golightan.TokenTypeText,
		python3.Python3LexerCLOSE_PAREN:        golightan.TokenTypeText,
		python3.Python3LexerCOMMA:              golightan.TokenTypeText,
		python3.Python3LexerCOLON:              golightan.TokenTypeText,
		python3.Python3LexerSEMI_COLON:         golightan.TokenTypeText,
		python3.Python3LexerPOWER:              golightan.TokenTypeText,
		python3.Python3LexerASSIGN:             golightan.TokenTypeText,
		python3.Python3LexerOPEN_BRACK:         golightan.TokenTypeText,
		python3.Python3LexerCLOSE_BRACK:        golightan.TokenTypeText,
		python3.Python3LexerOR_OP:              golightan.TokenTypeText,
		python3.Python3LexerXOR:                golightan.TokenTypeText,
		python3.Python3LexerAND_OP:             golightan.TokenTypeText,
		python3.Python3LexerLEFT_SHIFT:         golightan.TokenTypeText,
		python3.Python3LexerRIGHT_SHIFT:        golightan.TokenTypeText,
		python3.Python3LexerADD:                golightan.TokenTypeOperator,
		python3.Python3LexerMINUS:              golightan.TokenTypeOperator,
		python3.Python3LexerDIV:                golightan.TokenTypeOperator,
		python3.Python3LexerMOD:                golightan.TokenTypeOperator,
		python3.Python3LexerIDIV:               golightan.TokenTypeText,
		python3.Python3LexerNOT_OP:             golightan.TokenTypeText,
		python3.Python3LexerOPEN_BRACE:         golightan.TokenTypeText,
		python3.Python3LexerCLOSE_BRACE:        golightan.TokenTypeText,
		python3.Python3LexerLESS_THAN:          golightan.TokenTypeOperator,
		python3.Python3LexerGREATER_THAN:       golightan.TokenTypeOperator,
		python3.Python3LexerEQUALS:             golightan.TokenTypeOperator,
		python3.Python3LexerGT_EQ:              golightan.TokenTypeOperator,
		python3.Python3LexerLT_EQ:              golightan.TokenTypeOperator,
		python3.Python3LexerNOT_EQ_1:           golightan.TokenTypeOperator,
		python3.Python3LexerNOT_EQ_2:           golightan.TokenTypeOperator,
		python3.Python3LexerAT:                 golightan.TokenTypeText,
		python3.Python3LexerARROW:              golightan.TokenTypeText,
		python3.Python3LexerADD_ASSIGN:         golightan.TokenTypeOperator,
		python3.Python3LexerSUB_ASSIGN:         golightan.TokenTypeOperator,
		python3.Python3LexerMULT_ASSIGN:        golightan.TokenTypeOperator,
		python3.Python3LexerAT_ASSIGN:          golightan.TokenTypeOperator,
		python3.Python3LexerDIV_ASSIGN:         golightan.TokenTypeOperator,
		python3.Python3LexerMOD_ASSIGN:         golightan.TokenTypeOperator,
		python3.Python3LexerAND_ASSIGN:         golightan.TokenTypeOperator,
		python3.Python3LexerOR_ASSIGN:          golightan.TokenTypeOperator,
		python3.Python3LexerXOR_ASSIGN:         golightan.TokenTypeOperator,
		python3.Python3LexerLEFT_SHIFT_ASSIGN:  golightan.TokenTypeOperator,
		python3.Python3LexerRIGHT_SHIFT_ASSIGN: golightan.TokenTypeOperator,
		python3.Python3LexerPOWER_ASSIGN:       golightan.TokenTypeOperator,
		python3.Python3LexerIDIV_ASSIGN:        golightan.TokenTypeOperator,
		python3.Python3LexerSKIP_:              golightan.TokenTypeText,
		python3.Python3LexerUNKNOWN_CHAR:       golightan.TokenTypeText,
		python3.Python3LexerCOMMENT:            golightan.TokenTypeComment,
	}
}
