Token.Literal.String.Doc	u'"""The asyncio package, tracking PEP 3156."""'
Token.Text	u'\n'
Token.Text	u'\n'
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Name.Namespace	u'sys'
Token.Text	u'\n'
Token.Text	u'\n'
Token.Comment.Single	u'# The selectors module is in the stdlib in Python 3.4 but not in 3.3.'
Token.Text	u'\n'
Token.Comment.Single	u'# Do this first, so the other submodules can use "from . import selectors".'
Token.Text	u'\n'
Token.Comment.Single	u'# Prefer asyncio/selectors.py over the stdlib one, as ours may be newer.'
Token.Text	u'\n'
Token.Keyword	u'try'
Token.Punctuation	u':'
Token.Text	u'\n'
Token.Text	u'    '
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Name	u'selectors'
Token.Text	u'\n'
Token.Keyword	u'except'
Token.Text	u' '
Token.Name.Exception	u'ImportError'
Token.Punctuation	u':'
Token.Text	u'\n'
Token.Text	u'    '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Name.Namespace	u'selectors'
Token.Text	u'  '
Token.Comment.Single	u'# Will also be exported.'
Token.Text	u'\n'
Token.Text	u'\n'
Token.Keyword	u'if'
Token.Text	u' '
Token.Name	u'sys'
Token.Operator	u'.'
Token.Name	u'platform'
Token.Text	u' '
Token.Operator	u'=='
Token.Text	u' '
Token.Literal.String.Single	u"'"
Token.Literal.String.Single	u'win32'
Token.Literal.String.Single	u"'"
Token.Punctuation	u':'
Token.Text	u'\n'
Token.Text	u'    '
Token.Comment.Single	u'# Similar thing for _overlapped.'
Token.Text	u'\n'
Token.Text	u'    '
Token.Keyword	u'try'
Token.Punctuation	u':'
Token.Text	u'\n'
Token.Text	u'        '
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Name	u'_overlapped'
Token.Text	u'\n'
Token.Text	u'    '
Token.Keyword	u'except'
Token.Text	u' '
Token.Name.Exception	u'ImportError'
Token.Punctuation	u':'
Token.Text	u'\n'
Token.Text	u'        '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Name.Namespace	u'_overlapped'
Token.Text	u'  '
Token.Comment.Single	u'# Will also be exported.'
Token.Text	u'\n'
Token.Text	u'\n'
Token.Comment.Single	u'# This relies on each of the submodules having an __all__ variable.'
Token.Text	u'\n'
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.base_events'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Operator	u'*'
Token.Text	u'\n'
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.coroutines'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Operator	u'*'
Token.Text	u'\n'
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.events'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Operator	u'*'
Token.Text	u'\n'
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.futures'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Operator	u'*'
Token.Text	u'\n'
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.locks'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Operator	u'*'
Token.Text	u'\n'
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.protocols'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Operator	u'*'
Token.Text	u'\n'
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.queues'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Operator	u'*'
Token.Text	u'\n'
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.streams'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Operator	u'*'
Token.Text	u'\n'
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.subprocess'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Operator	u'*'
Token.Text	u'\n'
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.tasks'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Operator	u'*'
Token.Text	u'\n'
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.transports'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Operator	u'*'
Token.Text	u'\n'
Token.Text	u'\n'
Token.Name	u'__all__'
Token.Text	u' '
Token.Operator	u'='
Token.Text	u' '
Token.Punctuation	u'('
Token.Name	u'base_events'
Token.Operator	u'.'
Token.Name	u'__all__'
Token.Text	u' '
Token.Operator	u'+'
Token.Text	u'\n'
Token.Text	u'           '
Token.Name	u'coroutines'
Token.Operator	u'.'
Token.Name	u'__all__'
Token.Text	u' '
Token.Operator	u'+'
Token.Text	u'\n'
Token.Text	u'           '
Token.Name	u'events'
Token.Operator	u'.'
Token.Name	u'__all__'
Token.Text	u' '
Token.Operator	u'+'
Token.Text	u'\n'
Token.Text	u'           '
Token.Name	u'futures'
Token.Operator	u'.'
Token.Name	u'__all__'
Token.Text	u' '
Token.Operator	u'+'
Token.Text	u'\n'
Token.Text	u'           '
Token.Name	u'locks'
Token.Operator	u'.'
Token.Name	u'__all__'
Token.Text	u' '
Token.Operator	u'+'
Token.Text	u'\n'
Token.Text	u'           '
Token.Name	u'protocols'
Token.Operator	u'.'
Token.Name	u'__all__'
Token.Text	u' '
Token.Operator	u'+'
Token.Text	u'\n'
Token.Text	u'           '
Token.Name	u'queues'
Token.Operator	u'.'
Token.Name	u'__all__'
Token.Text	u' '
Token.Operator	u'+'
Token.Text	u'\n'
Token.Text	u'           '
Token.Name	u'streams'
Token.Operator	u'.'
Token.Name	u'__all__'
Token.Text	u' '
Token.Operator	u'+'
Token.Text	u'\n'
Token.Text	u'           '
Token.Name	u'subprocess'
Token.Operator	u'.'
Token.Name	u'__all__'
Token.Text	u' '
Token.Operator	u'+'
Token.Text	u'\n'
Token.Text	u'           '
Token.Name	u'tasks'
Token.Operator	u'.'
Token.Name	u'__all__'
Token.Text	u' '
Token.Operator	u'+'
Token.Text	u'\n'
Token.Text	u'           '
Token.Name	u'transports'
Token.Operator	u'.'
Token.Name	u'__all__'
Token.Punctuation	u')'
Token.Text	u'\n'
Token.Text	u'\n'
Token.Keyword	u'if'
Token.Text	u' '
Token.Name	u'sys'
Token.Operator	u'.'
Token.Name	u'platform'
Token.Text	u' '
Token.Operator	u'=='
Token.Text	u' '
Token.Literal.String.Single	u"'"
Token.Literal.String.Single	u'win32'
Token.Literal.String.Single	u"'"
Token.Punctuation	u':'
Token.Text	u'  '
Token.Comment.Single	u'# pragma: no cover'
Token.Text	u'\n'
Token.Text	u'    '
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.windows_events'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Operator	u'*'
Token.Text	u'\n'
Token.Text	u'    '
Token.Name	u'__all__'
Token.Text	u' '
Token.Operator	u'+'
Token.Operator	u'='
Token.Text	u' '
Token.Name	u'windows_events'
Token.Operator	u'.'
Token.Name	u'__all__'
Token.Text	u'\n'
Token.Keyword	u'else'
Token.Punctuation	u':'
Token.Text	u'\n'
Token.Text	u'    '
Token.Keyword.Namespace	u'from'
Token.Text	u' '
Token.Name.Namespace	u'.unix_events'
Token.Text	u' '
Token.Keyword.Namespace	u'import'
Token.Text	u' '
Token.Operator	u'*'
Token.Text	u'  '
Token.Comment.Single	u'# pragma: no cover'
Token.Text	u'\n'
Token.Text	u'    '
Token.Name	u'__all__'
Token.Text	u' '
Token.Operator	u'+'
Token.Operator	u'='
Token.Text	u' '
Token.Name	u'unix_events'
Token.Operator	u'.'
Token.Name	u'__all__'
Token.Text	u'\n'
